name: "traccc-cuda-seeding"
backend: "traccc"
max_batch_size: 0
input [
  {
    name: "CELL_POSITIONS"
    data_type: TYPE_INT64
    dims: [ -1, 4 ]
  },
  {
    name: "CELL_PROPERTIES"
    data_type: TYPE_FP32
    dims: [ -1, 2 ]
  }
]
output [
  {
    name: "SPACEPOINTS"
    data_type: TYPE_FP32
    dims: [ -1, 5 ]
  },
  {
    name: "SEEDS"
    data_type: TYPE_INT64
    dims: [ -1, 3 ]
  }
]
instance_group [
  {
    count: 4
    kind: KIND_GPU
    gpus: [0]
  }
]
parameters: {
  key: "pipeline_mode"
  value: { string_value: "SEEDING" }
}
